site_name: Data Catalog
site_author: Cegid Iberia
site_url: https://product@@ENV@@documentationsa.blob.core.windows.net/docs/@@REPONAME@@/
nav:
- 'Home': 'README.md' 
- 'Release Notes':
    - 'Release v6.5.10.0': 'release-notes/RN Visualtime.v6.5.10.0.md'
    - 'Release v6.5.12.0': 'release-notes/RN Visultime.v6.5.12.0.md'



theme:
    name: null
    custom_dir: devops-template